language: node_js
node_js:
  - 10.19.0
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - main
    - dev
deploy:
  provider: heroku
  api_key:
    secure: ADD_API_KEY_HERE
  app:
    main: node-hello-world91
    dev: node-hello-world-staging1
